---

application:
  client-origin-url: http://localhost:4040

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-gzgdh7hw4udvv70u.us.auth0.com/.well-known/jwks.json

okta:
  oauth2:
    issuer: https://dev-gzgdh7hw4udvv70u.us.auth0.com/
    audience: https://cvbuilder.monoinfinity.net/

...
