name: auto-build-deploy
on:
  push:
    branches:
      - "master"
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: checking allow to build
        run: |
          if [ ${{secrets.BUILD}} == ACTIVE ]
          then
            echo '------------------- ready to deploy --------------------'
          else
            echo 'not ready'
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build-check
    steps:
      - name: executing remote ssh commands using ssh key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ubuntu/app/minh/casptone-project/
            sudo docker-compose pull
            sudo docker-compose up -d
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
